/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Vistas;

/**
 *
 * @author guerr
 */

import Modelo.IdiomaPais;
import Modelo.Pais;
import DAO.IdiomaPaisDAO;
import Controlador.Conn;
import java.sql.Connection;
import java.sql.SQLException;
import java.util.List;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

public class VistaIdioma extends javax.swing.JFrame {
    private List<Pais> listaPaisesRecibida;
    private DefaultTableModel tablaIdiomasModel;
    private IdiomaPaisDAO idiomaDAO;
    private int idiomaSeleccionadoId = -1;
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(VistaIdioma.class.getName());

    public VistaIdioma() {
        initComponents();
    }
    
    public VistaIdioma(List<Pais> paises, Connection connection) {
        initComponents();
        this.setLocationRelativeTo(null);
        this.setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        this.listaPaisesRecibida = paises;
        this.idiomaDAO = new IdiomaPaisDAO();
        this.tablaIdiomasModel = (DefaultTableModel) jTable1.getModel();
        cargarPaisesEnComboBox();
    }


    private void cargarPaisesEnComboBox() {
        DefaultComboBoxModel<Pais> modelo = new DefaultComboBoxModel<>();
        for (Pais p : this.listaPaisesRecibida) {
            modelo.addElement(p);
        }
        cbPaises.setModel(modelo);
        actualizarTablaIdiomas();
    }
    
    private Pais obtenerPaisPorId(int idPais) {
        for (Pais pais : listaPaisesRecibida) {
            if (pais.getIdPais() == idPais) {
                return pais;
            }
        }
        return null;
    }
    
    private void actualizarTablaIdiomas() {
        tablaIdiomasModel.setRowCount(0);
        Pais paisSeleccionado = (Pais) cbPaises.getSelectedItem();
        if (paisSeleccionado != null) {
            try {
                List<IdiomaPais> idiomas = idiomaDAO.obtenerIdiomasPorPais(paisSeleccionado.getIdPais());

                for (IdiomaPais idioma : idiomas) {
                    Object[] fila = {
                        idioma.getIdIdioma(),                    // Columna 0: ID
                        idioma.getIdioma(),                      // Columna 1: Idioma
                        idioma.getPorcentajeHablante() + "%",    // Columna 2: Porcentaje
                        idioma.isEsOficial()                    // Columna 3: Es oficial (Boolean)
                    };
                    tablaIdiomasModel.addRow(fila);
                }
            } catch (SQLException e) {
                JOptionPane.showMessageDialog(this, "Error al cargar idiomas: " + e.getMessage(), 
                                            "Error", JOptionPane.ERROR_MESSAGE);
            }
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jLayeredPane1 = new javax.swing.JLayeredPane();
        lblTitulo = new javax.swing.JLabel();
        txtIdioma = new javax.swing.JTextField();
        lblIdioma = new javax.swing.JLabel();
        txtPorcentaje = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        cbPaises = new javax.swing.JComboBox<>();
        lbPais = new javax.swing.JLabel();
        RbOficial = new javax.swing.JRadioButton();
        jLabel2 = new javax.swing.JLabel();
        BtnnAgregar = new javax.swing.JButton();
        BtnnEditar = new javax.swing.JButton();
        jLayeredPane2 = new javax.swing.JLayeredPane();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        bttnAtras = new javax.swing.JButton();

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLayeredPane1.setPreferredSize(new java.awt.Dimension(250, 288));

        lblTitulo.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        lblTitulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTitulo.setText("Registro Idioma internacional");

        txtIdioma.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtIdiomaActionPerformed(evt);
            }
        });
        txtIdioma.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtIdiomaKeyTyped(evt);
            }
        });

        lblIdioma.setText("Idioma");

        txtPorcentaje.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtPorcentajeKeyTyped(evt);
            }
        });

        jLabel1.setText("Porcentaje");

        cbPaises.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbPaisesActionPerformed(evt);
            }
        });

        lbPais.setText("Pais");

        RbOficial.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RbOficialActionPerformed(evt);
            }
        });

        jLabel2.setText("Es Oficial");

        BtnnAgregar.setText("Agregar");
        BtnnAgregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnnAgregarActionPerformed(evt);
            }
        });

        BtnnEditar.setText("Editar");
        BtnnEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnnEditarActionPerformed(evt);
            }
        });

        jLayeredPane1.setLayer(lblTitulo, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(txtIdioma, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(lblIdioma, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(txtPorcentaje, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(jLabel1, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(cbPaises, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(lbPais, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(RbOficial, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(jLabel2, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(BtnnAgregar, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(BtnnEditar, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout jLayeredPane1Layout = new javax.swing.GroupLayout(jLayeredPane1);
        jLayeredPane1.setLayout(jLayeredPane1Layout);
        jLayeredPane1Layout.setHorizontalGroup(
            jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jLayeredPane1Layout.createSequentialGroup()
                .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jLayeredPane1Layout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addComponent(lblTitulo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jLayeredPane1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jLayeredPane1Layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(jLabel1))
                            .addGroup(jLayeredPane1Layout.createSequentialGroup()
                                .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblIdioma)
                                    .addComponent(lbPais)
                                    .addComponent(jLabel2))
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(RbOficial)
                            .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(cbPaises, javax.swing.GroupLayout.Alignment.TRAILING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(txtPorcentaje, javax.swing.GroupLayout.DEFAULT_SIZE, 180, Short.MAX_VALUE)
                                .addComponent(txtIdioma))))
                    .addGroup(jLayeredPane1Layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(BtnnAgregar)
                        .addGap(18, 18, 18)
                        .addComponent(BtnnEditar)))
                .addContainerGap())
        );
        jLayeredPane1Layout.setVerticalGroup(
            jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jLayeredPane1Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(lblTitulo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cbPaises, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbPais))
                .addGap(47, 47, 47)
                .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtIdioma, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblIdioma))
                .addGap(18, 18, 18)
                .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtPorcentaje, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addGap(18, 18, 18)
                .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(RbOficial)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 33, Short.MAX_VALUE)
                .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BtnnEditar)
                    .addComponent(BtnnAgregar))
                .addGap(21, 21, 21))
        );

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "ID", "Idioma", "Hablantes (%)", "Es oficial"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Boolean.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(jTable1);

        bttnAtras.setText("Atras");
        bttnAtras.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bttnAtrasActionPerformed(evt);
            }
        });

        jLayeredPane2.setLayer(jScrollPane2, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane2.setLayer(bttnAtras, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout jLayeredPane2Layout = new javax.swing.GroupLayout(jLayeredPane2);
        jLayeredPane2.setLayout(jLayeredPane2Layout);
        jLayeredPane2Layout.setHorizontalGroup(
            jLayeredPane2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jLayeredPane2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 452, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jLayeredPane2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(bttnAtras)
                .addContainerGap())
        );
        jLayeredPane2Layout.setVerticalGroup(
            jLayeredPane2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jLayeredPane2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 222, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(bttnAtras)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLayeredPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLayeredPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLayeredPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(jLayeredPane2)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void RbOficialActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RbOficialActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_RbOficialActionPerformed

    private void cbPaisesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbPaisesActionPerformed
        actualizarTablaIdiomas();
    }//GEN-LAST:event_cbPaisesActionPerformed

    private void BtnnAgregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnnAgregarActionPerformed
        Pais paisSeleccionado = (Pais) cbPaises.getSelectedItem();
        if (paisSeleccionado == null) {
            JOptionPane.showMessageDialog(this, "Debe seleccionar un pais", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }
        
        if (paisSeleccionado.getIdPais() == -1) {
            JOptionPane.showMessageDialog(this, "No puede agregar registros en Global", "Error", JOptionPane.WARNING_MESSAGE);
            return;
        }

        if (txtIdioma.getText().isEmpty() || txtPorcentaje.getText().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Debe rellenar los campos de idioma y porcentaje", "Campos incompletos", JOptionPane.WARNING_MESSAGE);
            return;
        }

        try {
            String nombreIdioma = txtIdioma.getText();
            float porcentaje = Float.parseFloat(txtPorcentaje.getText());
            boolean esOficial = RbOficial.isSelected();
            
            IdiomaPais nuevoIdioma = new IdiomaPais(paisSeleccionado.getIdPais(), nombreIdioma, esOficial, porcentaje);
            
            int idGenerado = idiomaDAO.insertarIdioma(nuevoIdioma);
            
            if (idGenerado != -1) {
                nuevoIdioma.setIdIdioma(idGenerado);
                actualizarTablaIdiomas();
                txtIdioma.setText("");
                txtPorcentaje.setText("");
                RbOficial.setSelected(false);

                JOptionPane.showMessageDialog(this, "Idioma '" + nombreIdioma + "' agregado a " + paisSeleccionado.getNombre() + ".", "Éxito", JOptionPane.INFORMATION_MESSAGE);
            }
            
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "El porcentaje debe ser un número válido", "Error de Formato", JOptionPane.ERROR_MESSAGE);
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(this, "Error al guardar idioma: " + e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_BtnnAgregarActionPerformed

    private void BtnnEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnnEditarActionPerformed
        if (idiomaSeleccionadoId == -1) {
            JOptionPane.showMessageDialog(this, "Primero debe seleccionar un idioma de la tabla", "Aviso", JOptionPane.WARNING_MESSAGE);
            return;
        }

        try {
            IdiomaPais idiomaAModificar = idiomaDAO.obtenerIdiomaPorId(idiomaSeleccionadoId);

            if (idiomaAModificar != null) {
                idiomaAModificar.setIdioma(txtIdioma.getText());
                idiomaAModificar.setPorcentajeHablante(Float.parseFloat(txtPorcentaje.getText()));
                idiomaAModificar.setEsOficial(RbOficial.isSelected());

                boolean actualizado = idiomaDAO.actualizarIdioma(idiomaAModificar);

                if (actualizado) {
                    actualizarTablaIdiomas();
                    JOptionPane.showMessageDialog(this, "Idioma modificado con éxito", "Éxito", JOptionPane.INFORMATION_MESSAGE);

                    // Limpiar después de editar
                    txtIdioma.setText("");
                    txtPorcentaje.setText("");
                    RbOficial.setSelected(false);
                    idiomaSeleccionadoId = -1;
                }
            }

        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "El porcentaje debe ser un número válido", "Error de Formato", JOptionPane.ERROR_MESSAGE);
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(this, "Error al actualizar idioma: " + e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_BtnnEditarActionPerformed

    private void bttnAtrasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bttnAtrasActionPerformed
        this.dispose();
    }//GEN-LAST:event_bttnAtrasActionPerformed

    private void txtIdiomaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtIdiomaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtIdiomaActionPerformed

    private void txtIdiomaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtIdiomaKeyTyped
        if(txtIdioma.getText().length() > 8 || !Character.isLetter(evt.getKeyChar())){
            evt.consume();
        }
    }//GEN-LAST:event_txtIdiomaKeyTyped

    private void txtPorcentajeKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtPorcentajeKeyTyped
        char tecla = evt.getKeyChar();
        if (!Character.isDigit(tecla) && tecla != '.' && tecla != '\b') {
            evt.consume();
        }
        if (txtPorcentaje.getText().length() > 5) {
            evt.consume();
        }
    }//GEN-LAST:event_txtPorcentajeKeyTyped

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        int fila = jTable1.getSelectedRow();
        if (fila != -1) {
            try {
                this.idiomaSeleccionadoId = (int) tablaIdiomasModel.getValueAt(fila, 0); // ← GUARDAR ID

                IdiomaPais idiomaSeleccionado = idiomaDAO.obtenerIdiomaPorId(idiomaSeleccionadoId);

                if (idiomaSeleccionado != null) {
                    txtIdioma.setText(idiomaSeleccionado.getIdioma());
                    txtPorcentaje.setText(String.valueOf(idiomaSeleccionado.getPorcentajeHablante()));
                    RbOficial.setSelected(idiomaSeleccionado.isEsOficial());

                    Pais paisDelIdioma = obtenerPaisPorId(idiomaSeleccionado.getIdPais());
                    if (paisDelIdioma != null) {
                        cbPaises.setSelectedItem(paisDelIdioma);
                    }
                }

            } catch (SQLException e) {
                JOptionPane.showMessageDialog(this, "Error al cargar datos del idioma: " + e.getMessage(), 
                                            "Error", JOptionPane.ERROR_MESSAGE);
                logger.warning("Error al obtener idioma por ID: " + e.getMessage());
            } catch (Exception e) {
                logger.warning("Error inesperado: " + e.getMessage());
            }
        }
    }//GEN-LAST:event_jTable1MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new VistaIdioma().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnnAgregar;
    private javax.swing.JButton BtnnEditar;
    private javax.swing.JRadioButton RbOficial;
    private javax.swing.JButton bttnAtras;
    private javax.swing.JComboBox<Modelo.Pais> cbPaises;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLayeredPane jLayeredPane1;
    private javax.swing.JLayeredPane jLayeredPane2;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JLabel lbPais;
    private javax.swing.JLabel lblIdioma;
    private javax.swing.JLabel lblTitulo;
    private javax.swing.JTextField txtIdioma;
    private javax.swing.JTextField txtPorcentaje;
    // End of variables declaration//GEN-END:variables
}
