/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Vistas;

import Controlador.Conn;
import DAO.PaisDAO;
import Modelo.Pais;
import java.sql.SQLException;
import java.util.List;
import javax.swing.JOptionPane;

/**
 *
 * @author aacev
 */
public class VistaMenu extends javax.swing.JFrame {
    
    private boolean esAdmin;
    private String nombreUsuario;
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(VistaMenu.class.getName());

    /**
     * Creates new form VistaMenu
     */
    public VistaMenu(boolean esAdmin, String nombreUsuario) {
        initComponents();
        setLocationRelativeTo(null);
        this.esAdmin = esAdmin;
        this.nombreUsuario = nombreUsuario;
        lpControlDeUsuarios.setVisible(esAdmin);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblTitulo = new javax.swing.JLabel();
        lpControlDeUsuarios = new javax.swing.JLayeredPane();
        bttnControlDeUsuario = new javax.swing.JButton();
        jLayeredPane1 = new javax.swing.JLayeredPane();
        lblConsultaDeDatos = new javax.swing.JLabel();
        bttnPais = new javax.swing.JButton();
        bttnCiudad = new javax.swing.JButton();
        bttnIdioma = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lblTitulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTitulo.setText("Registro poblacional internacional");

        bttnControlDeUsuario.setText("Control de usuarios");
        bttnControlDeUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bttnControlDeUsuarioActionPerformed(evt);
            }
        });

        lpControlDeUsuarios.setLayer(bttnControlDeUsuario, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout lpControlDeUsuariosLayout = new javax.swing.GroupLayout(lpControlDeUsuarios);
        lpControlDeUsuarios.setLayout(lpControlDeUsuariosLayout);
        lpControlDeUsuariosLayout.setHorizontalGroup(
            lpControlDeUsuariosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(lpControlDeUsuariosLayout.createSequentialGroup()
                .addGap(109, 109, 109)
                .addComponent(bttnControlDeUsuario)
                .addContainerGap(109, Short.MAX_VALUE))
        );
        lpControlDeUsuariosLayout.setVerticalGroup(
            lpControlDeUsuariosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(bttnControlDeUsuario)
        );

        lblConsultaDeDatos.setText("Consulta de datos:");

        bttnPais.setText("Pais");
        bttnPais.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bttnPaisActionPerformed(evt);
            }
        });

        bttnCiudad.setText("Ciudad");
        bttnCiudad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bttnCiudadActionPerformed(evt);
            }
        });

        bttnIdioma.setText("Idioma");
        bttnIdioma.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bttnIdiomaActionPerformed(evt);
            }
        });

        jLayeredPane1.setLayer(lblConsultaDeDatos, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(bttnPais, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(bttnCiudad, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(bttnIdioma, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout jLayeredPane1Layout = new javax.swing.GroupLayout(jLayeredPane1);
        jLayeredPane1.setLayout(jLayeredPane1Layout);
        jLayeredPane1Layout.setHorizontalGroup(
            jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jLayeredPane1Layout.createSequentialGroup()
                .addGap(126, 126, 126)
                .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lblConsultaDeDatos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(bttnPais, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(bttnCiudad, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(bttnIdioma, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jLayeredPane1Layout.setVerticalGroup(
            jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jLayeredPane1Layout.createSequentialGroup()
                .addComponent(lblConsultaDeDatos)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(bttnPais)
                .addGap(12, 12, 12)
                .addComponent(bttnCiudad)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(bttnIdioma)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblTitulo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lpControlDeUsuarios)
                    .addComponent(jLayeredPane1))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(lblTitulo)
                .addGap(18, 18, 18)
                .addComponent(lpControlDeUsuarios, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLayeredPane1)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bttnControlDeUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bttnControlDeUsuarioActionPerformed

    }//GEN-LAST:event_bttnControlDeUsuarioActionPerformed

    private void bttnPaisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bttnPaisActionPerformed
            VistaPais vistaPais = new VistaPais();
            vistaPais.setVisible(true);
    }//GEN-LAST:event_bttnPaisActionPerformed

    private void bttnCiudadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bttnCiudadActionPerformed
    try {
        PaisDAO paisDAO = new PaisDAO();
        List<Pais> listaPaises = paisDAO.obtenerTodosPaises();
        
        VistaCiudad vistaCiudad = new VistaCiudad(listaPaises, Conn.getConnection());
        vistaCiudad.setVisible(true);
        
    } catch (SQLException e) {
        JOptionPane.showMessageDialog(this, "Error al cargar países: " + e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
    }
    }//GEN-LAST:event_bttnCiudadActionPerformed

    private void bttnIdiomaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bttnIdiomaActionPerformed
    try {
        PaisDAO paisDAO = new PaisDAO();
        List<Pais> listaPaises = paisDAO.obtenerTodosPaises();
        
        VistaIdioma vistaIdioma = new VistaIdioma(listaPaises, Conn.getConnection());
        vistaIdioma.setVisible(true);
        
    } catch (SQLException e) {
        JOptionPane.showMessageDialog(this, "Error al cargar países: " + e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
    }
    }//GEN-LAST:event_bttnIdiomaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bttnCiudad;
    private javax.swing.JButton bttnControlDeUsuario;
    private javax.swing.JButton bttnIdioma;
    private javax.swing.JButton bttnPais;
    private javax.swing.JLayeredPane jLayeredPane1;
    private javax.swing.JLabel lblConsultaDeDatos;
    private javax.swing.JLabel lblTitulo;
    private javax.swing.JLayeredPane lpControlDeUsuarios;
    // End of variables declaration//GEN-END:variables

    
}
