/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

package Vistas;

import Modelo.Ciudad;
import Modelo.Pais;
import DAO.CiudadDAO;
import java.sql.Connection;
import java.util.List;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
/**
 *
 * @author guerr
 */

public class VistaCiudad extends javax.swing.JFrame {
    private List<Pais> listaPaisesRecibida;
    private DefaultTableModel tablaCiudadesModel;
    private CiudadDAO ciudadDAO;
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(VistaCiudad.class.getName());

    public VistaCiudad() {
        initComponents();
    }

    public VistaCiudad(List<Pais> paises, Connection connection) {
        initComponents();
        this.setLocationRelativeTo(null);
        this.listaPaisesRecibida = paises;
        this.ciudadDAO = new CiudadDAO(connection);
        this.tablaCiudadesModel = (DefaultTableModel) jTable1.getModel();
        cargarPaisesEnComboBox();
    }
    
    private void cargarPaisesEnComboBox() {
        DefaultComboBoxModel<Pais> modelo = new DefaultComboBoxModel<>();
        
        try {
            Pais opcionGlobal = new Pais();
            opcionGlobal.setIdPais(-1);
            opcionGlobal.setNombre("GLOBAL (Ver todas)"); 
            opcionGlobal.setContinente("N/A"); opcionGlobal.setRegion("N/A"); 
            opcionGlobal.setSuperficie(0); opcionGlobal.setAnioIndependencia(0);
            opcionGlobal.setPoblacion(0); opcionGlobal.setExpectLife(0); 
            opcionGlobal.setPib(0); opcionGlobal.setGobierno("N/A"); 
            opcionGlobal.setJefeGobierno("N/A"); opcionGlobal.setCapitalNombre("N/A");
            opcionGlobal.setCodPais("GLB");
            
            modelo.addElement(opcionGlobal);

            for (Pais p : this.listaPaisesRecibida) {
                modelo.addElement(p);
            }
            
            jbPaises.setModel(modelo);
            
        } catch (Exception e) {
            System.out.println("Error al crear opción global");
        }
    }
    
    private void actualizarTablaCiudades() {
        tablaCiudadesModel.setRowCount(0);
        Pais paisSeleccionado = (Pais) jbPaises.getSelectedItem();
        
        if (paisSeleccionado != null) {
            try {
                List<Ciudad> ciudades;
                if (paisSeleccionado.getIdPais() == -1) {
                    ciudades = ciudadDAO.obtenerTodas(); 
                } else {
                    ciudades = ciudadDAO.obtenerPorPais(paisSeleccionado.getIdPais());
                }

                for (Ciudad c : ciudades) {
                    Object[] fila = {
                        c.getIdCiudad(),
                        c.getNombre(),
                        c.getDistrito(),
                        c.getPoblacion(),
                        c.isEsCapital()
                    };
                    tablaCiudadesModel.addRow(fila);
                }
            } catch (Exception e) {
                javax.swing.JOptionPane.showMessageDialog(this, "Error al cargar ciudades: " + e.getMessage());
            }
        }
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLayeredPane1 = new javax.swing.JLayeredPane();
        jLabel1 = new javax.swing.JLabel();
        lbNombre = new javax.swing.JLabel();
        txtNombre = new javax.swing.JTextField();
        txtDistrito = new javax.swing.JTextField();
        lbDistrito = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtPoblacion = new javax.swing.JTextField();
        jbPaises = new javax.swing.JComboBox<>();
        BtnnAgregar = new javax.swing.JButton();
        BtnnEditar = new javax.swing.JButton();
        rbEsCapital = new javax.swing.JRadioButton();
        lblEsCapital = new javax.swing.JLabel();
        jLayeredPane2 = new javax.swing.JLayeredPane();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        bttnAtras = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Pais");

        lbNombre.setText("Nombre");

        txtNombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNombreActionPerformed(evt);
            }
        });
        txtNombre.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtNombreKeyTyped(evt);
            }
        });

        txtDistrito.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtDistritoKeyTyped(evt);
            }
        });

        lbDistrito.setText("Distrito");

        jLabel2.setText("Poblacion");

        txtPoblacion.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtPoblacionKeyTyped(evt);
            }
        });

        jbPaises.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbPaisesActionPerformed(evt);
            }
        });

        BtnnAgregar.setText("Agregar");
        BtnnAgregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnnAgregarActionPerformed(evt);
            }
        });

        BtnnEditar.setText("Editar");
        BtnnEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnnEditarActionPerformed(evt);
            }
        });

        rbEsCapital.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbEsCapitalActionPerformed(evt);
            }
        });

        lblEsCapital.setText("Es capital");

        jLayeredPane1.setLayer(jLabel1, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(lbNombre, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(txtNombre, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(txtDistrito, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(lbDistrito, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(jLabel2, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(txtPoblacion, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(jbPaises, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(BtnnAgregar, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(BtnnEditar, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(rbEsCapital, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(lblEsCapital, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout jLayeredPane1Layout = new javax.swing.GroupLayout(jLayeredPane1);
        jLayeredPane1.setLayout(jLayeredPane1Layout);
        jLayeredPane1Layout.setHorizontalGroup(
            jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jLayeredPane1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jLayeredPane1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(BtnnAgregar)
                        .addGap(18, 18, 18)
                        .addComponent(BtnnEditar)
                        .addContainerGap())
                    .addGroup(jLayeredPane1Layout.createSequentialGroup()
                        .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(lbNombre)
                            .addComponent(lbDistrito)
                            .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel1)
                            .addComponent(lblEsCapital, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtDistrito, javax.swing.GroupLayout.DEFAULT_SIZE, 214, Short.MAX_VALUE)
                            .addComponent(txtNombre)
                            .addComponent(txtPoblacion)
                            .addComponent(jbPaises, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(jLayeredPane1Layout.createSequentialGroup()
                                .addComponent(rbEsCapital)
                                .addGap(0, 0, Short.MAX_VALUE))))))
        );
        jLayeredPane1Layout.setVerticalGroup(
            jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jLayeredPane1Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jLayeredPane1Layout.createSequentialGroup()
                        .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(jbPaises, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(24, 24, 24)
                        .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lbNombre)
                            .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtDistrito, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lbDistrito))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(txtPoblacion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(rbEsCapital))
                    .addComponent(lblEsCapital))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BtnnAgregar)
                    .addComponent(BtnnEditar))
                .addGap(19, 19, 19))
        );

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "ID", "Nombre", "Distrito", "Poblacion", "Es capital"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.Object.class, java.lang.Object.class, java.lang.Integer.class, java.lang.Boolean.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        bttnAtras.setText("Atras");
        bttnAtras.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bttnAtrasActionPerformed(evt);
            }
        });

        jLayeredPane2.setLayer(jScrollPane1, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane2.setLayer(bttnAtras, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout jLayeredPane2Layout = new javax.swing.GroupLayout(jLayeredPane2);
        jLayeredPane2.setLayout(jLayeredPane2Layout);
        jLayeredPane2Layout.setHorizontalGroup(
            jLayeredPane2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jLayeredPane2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 452, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jLayeredPane2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(bttnAtras)
                .addContainerGap())
        );
        jLayeredPane2Layout.setVerticalGroup(
            jLayeredPane2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jLayeredPane2Layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 241, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(bttnAtras)
                .addGap(0, 18, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLayeredPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLayeredPane2)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLayeredPane2)
                    .addComponent(jLayeredPane1))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtNombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNombreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNombreActionPerformed

    private void BtnnAgregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnnAgregarActionPerformed
        Pais paisSeleccionado = (Pais) jbPaises.getSelectedItem();
    
        if (paisSeleccionado == null) {
            JOptionPane.showMessageDialog(this, "Debe seleccionar un pais", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }
        if (paisSeleccionado.getIdPais() == -1) {
            JOptionPane.showMessageDialog(this, "No puede agregar registros en Global", "Error", JOptionPane.WARNING_MESSAGE);
            return;
        }
        if (txtNombre.getText().isEmpty() || txtDistrito.getText().isEmpty() || txtPoblacion.getText().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Complete todos los campos de la ciudad", "Campos incompletos", JOptionPane.WARNING_MESSAGE);
            return;
        }
        try {
            String nombreCiudad = txtNombre.getText();
            String distrito = txtDistrito.getText();
            int poblacion = Integer.parseInt(txtPoblacion.getText());
            boolean esCapital = rbEsCapital.isSelected();
            
            Ciudad nuevaCiudad = new Ciudad(paisSeleccionado.getIdPais(), nombreCiudad, distrito, poblacion, esCapital);
            
            ciudadDAO.insertar(nuevaCiudad);
            
            txtNombre.setText("");
            txtDistrito.setText("");
            txtPoblacion.setText("");
            rbEsCapital.setSelected(false);
            JOptionPane.showMessageDialog(this, "Ciudad '" + nombreCiudad + "' agregada a " + paisSeleccionado.getNombre() + " exitosamente.", "Éxito", JOptionPane.INFORMATION_MESSAGE);
            actualizarTablaCiudades();
            
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "La población debe ser un numero valido", "Error de Formato", JOptionPane.ERROR_MESSAGE);
        } catch (Exception ex) {
            System.getLogger(VistaCiudad.class.getName()).log(System.Logger.Level.ERROR, (String) null, ex);
        }
    }//GEN-LAST:event_BtnnAgregarActionPerformed

    private void BtnnEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnnEditarActionPerformed
        int filaSeleccionada = jTable1.getSelectedRow();
        if (filaSeleccionada == -1) {
            JOptionPane.showMessageDialog(this, "Primero debe consultar la ciudad que desea editar", "Aviso", JOptionPane.WARNING_MESSAGE);
            return;
        }

        try {
            int idCiudad = (int) tablaCiudadesModel.getValueAt(filaSeleccionada, 0);
            
            Ciudad ciudadAModificar = ciudadDAO.obtenerPorId(idCiudad);
            
            if (ciudadAModificar != null) {

                ciudadAModificar.setNombre(txtNombre.getText());
                ciudadAModificar.setDistrito(txtDistrito.getText());
                ciudadAModificar.setPoblacion(Integer.parseInt(txtPoblacion.getText()));
                ciudadAModificar.setEsCapital(rbEsCapital.isSelected());
                
                ciudadDAO.actualizar(ciudadAModificar);
                
                actualizarTablaCiudades();
                txtNombre.setText("");
                txtDistrito.setText("");
                txtPoblacion.setText("");
                rbEsCapital.setSelected(false);
                JOptionPane.showMessageDialog(this, "Ciudad modificada con exito", "Exito", JOptionPane.INFORMATION_MESSAGE);
            }
            
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "La poblacion debe ser un número valido", "Error de Formato", JOptionPane.ERROR_MESSAGE);
        } catch (Exception ex) {
            System.getLogger(VistaCiudad.class.getName()).log(System.Logger.Level.ERROR, (String) null, ex);
        }
    }//GEN-LAST:event_BtnnEditarActionPerformed

    private void jbPaisesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbPaisesActionPerformed
        actualizarTablaCiudades();
    }//GEN-LAST:event_jbPaisesActionPerformed

    private void bttnAtrasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bttnAtrasActionPerformed
        this.dispose();
    }//GEN-LAST:event_bttnAtrasActionPerformed

    private void txtNombreKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNombreKeyTyped
        if(txtNombre.getText().length() > 10 || !Character.isLetter(evt.getKeyChar())){
            evt.consume();
        }
    }//GEN-LAST:event_txtNombreKeyTyped

    private void txtDistritoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtDistritoKeyTyped
        if(txtDistrito.getText().length() > 10 || !Character.isLetter(evt.getKeyChar())){
            evt.consume();
        }
    }//GEN-LAST:event_txtDistritoKeyTyped

    private void txtPoblacionKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtPoblacionKeyTyped
        if(txtPoblacion.getText().length() > 10 || !Character.isDigit(evt.getKeyChar())){
            evt.consume();
        }
    }//GEN-LAST:event_txtPoblacionKeyTyped

    private void rbEsCapitalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbEsCapitalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rbEsCapitalActionPerformed

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        int fila = jTable1.getSelectedRow();
        if (fila != -1) {
            String nombre = tablaCiudadesModel.getValueAt(fila, 1).toString();     // Columna 1: Nombre
            String distrito = tablaCiudadesModel.getValueAt(fila, 2).toString();   // Columna 2: Distrito
            String poblacion = tablaCiudadesModel.getValueAt(fila, 3).toString();  // Columna 3: Población
            txtNombre.setText(nombre);
            txtDistrito.setText(distrito);
            txtPoblacion.setText(poblacion);

            try {
                int idCiudad = (int) tablaCiudadesModel.getValueAt(fila, 0);       // Columna 0: ID
                Ciudad ciudad = ciudadDAO.obtenerPorId(idCiudad);
                if (ciudad != null) {
                    rbEsCapital.setSelected(ciudad.isEsCapital());
                }
            } catch (Exception e) {
                logger.warning("Error al obtener datos de capital: " + e.getMessage());
            }
        }
    }//GEN-LAST:event_jTable1MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new VistaCiudad().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnnAgregar;
    private javax.swing.JButton BtnnEditar;
    private javax.swing.JButton bttnAtras;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLayeredPane jLayeredPane1;
    private javax.swing.JLayeredPane jLayeredPane2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JComboBox<Modelo.Pais> jbPaises;
    private javax.swing.JLabel lbDistrito;
    private javax.swing.JLabel lbNombre;
    private javax.swing.JLabel lblEsCapital;
    private javax.swing.JRadioButton rbEsCapital;
    private javax.swing.JTextField txtDistrito;
    private javax.swing.JTextField txtNombre;
    private javax.swing.JTextField txtPoblacion;
    // End of variables declaration//GEN-END:variables
}
